version: "3.9"

services:
  # --- API .NET 8 ---
  api:
    container_name: api
    build:
      context: ./backend/App
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq
    networks:
      - app_network

  # --- RabbitMQ ---
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"    # Porta de conexão AMQP
      - "15672:15672"  # Painel de administração web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app_network

  # --- Frontend React + Vite ---
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_BASE_URL=http://localhost:5000
    depends_on:
      - api
    networks:
      - app_network

networks:
  app_network:
    driver: bridge